### ISSUE TITLE
Running on __init__.py files removes all imports

### ISSUE THREAD

**Issue by commentator8** [miki725/importanize#61]
I have an `__init__.py` file with the following content:

`from .first import Second.
`

After running `importanize  --config=setup.cfg src/dir/__init__.py --print -v` i get this output

=============================
                                                               
src\dir\__init__.py
                                                                                           =============================

where it deletes all my imports in the file (this was a trivial example, but in general all imports are deleted resulting in other usages breaking).

Is this by design?

**Comment by miki725** [comment]
this is expected behavior now due to `unused_imports` plugin which is enabled by default https://github.com/miki725/importanize#unused-imports

you can either disable that plugin:

if you wish to disable it either use `allow_plugins` or `plugins` configuration options or `--no-plugins` parameter. https://github.com/miki725/importanize#configuration-options

or add `# noqa` comment to that import statement which will ignore that statement

**Comment by miki725** [comment]
added better docs in https://github.com/miki725/importanize/commit/0475aba0ad82ffd5da772cb5a3cc4a171d308c82
